golioth/golioth-zephyr-sdk

- zephyr/module.yml
This will give information to 'twister' (indirectly by executing
zephyr/scripts/zephyr_module.py first) about where samples are stored.
Related to following comment (from https://devzone.nordicsemi.com/f/nordic-q-a/81347/external-modules-with-visual-studio-code-extension):
> You are correct that the extension looks for samples in specific folders. The convention is to look in <toplevel>/applications or <toplevel>/samples folder. This is a convention for extra modules in NCS such as homekit/find-my. This means that if you modify the west.yml to put your SDK in the top level, i.e., remove the path:
> zephyr: provide path to samples/ in module.yml

- samples/dfu/README.rst
- samples/lightdb_stream/README.rst
New DFU mechanism differs in how artifacts are uploaded to cloud, how
releases are created and how to trigger a new firmware release rollout.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/73"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: dfu: update README to match new DFU mechanism

- west.yml
There were many improvements across the tree since the last stable
release. Use the newest Zephyr version to keep up with Zephyr
development.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/66"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump Zephyr to tip of 'main'

- net/golioth/system_client.c
Check PSK length at build time, so user will be notified early about PSK
being too big for use with mbedTLS.
So far we are fixed on using mbedTLS, so use configured PSK length as
the length of buffer for storing PSK for Golioth.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/79"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> system_client: check mbedTLS PSK length at build time and use it for runtime (config) buffer length

- net/golioth/system_client.c
NCS uses downstream Zephyr, which does not have
CONFIG_MBEDTLS_PSK_MAX_LEN introduced yet. Workaround that and assume
maximum 64 bytes of PSK.
Fixes: 7a53ca37fb1b ("net: golioth: system_client: check PSK length at
build time")
Fixes: d896d0a662d2 ("net: golioth: system_client: use mbedTLS PSK
length")
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> net: golioth: fix mbedTLS PSK length with NCS

- .gitlab-ci.yml
This file contains build errors, which are useful for figuring out what
has gone wrong.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> gitlab-ci: add build.log to artifacts

- .checkpatch.conf
- .gitlint
- scripts/gitlint/commit_rules.py
Recently CONTRIBUTING.md was introduced, which states that each commit should have Signed-off-by line. Enforce that in gitlint and checkpatch workflows.
gitlint: https://github.com/golioth/zephyr-sdk/actions/runs/1548716866
checkpatch: https://github.com/golioth/zephyr-sdk/actions/runs/1548716858
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/134"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: enforce Signed-off-by

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
This workflow will automatically check if commits are compliant with
configured pre-commit rules.
See how it detects missing newlines: https://github.com/golioth/zephyr-sdk/actions/runs/1548709001
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> github-ci: create pre-commit workflow

- samples/lightdb_led/src/main.c
The original LightDB demonstrated several different features in one sample.  The presence of the counter in the LED example is an artifact of this previous intent.  The counter is unrelated to the LED handling and is represented in a separate sample.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> remove counter

- README.rst
This command is not required for a long time already. Remove it from
README in order not to confuse users. Leave it in CI (GitHub and
GitLab), as it is handy to be able to test new features from Zephyr from
time to time (without intension of merging those patches to main
branch).
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/144"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> README: remove `west patch` step

- net/golioth/Kconfig
- net/golioth/system_client.c
- samples/dfu/src/main.c
- west.yml
ESP32 mcuboot support has been integrated in the last few weeks, so bump
Zephyr version in order to support DFU for ESP32 targets.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump Zephyr to tip of main

- samples/dfu/README.rst
This (currently old) version of readme-espressif.md file specifies
offset of bootloader when flashing it on target, while the newest
version (on tip of main) does not reference any specific value and it is
not trivial to figure it out.
As this readme file might quickly evolve over time, let's stick to a
last "known to work" version of it.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: dfu: reference specific revision of readme-espressif.md

- README.rst
Use https instead of git, which will allow users with read-only access
to initialize repository.
Also use 'zephyr-sdk.git' instead of 'zephyr.git', which is due to
project rename few months ago.
'west init' implicitly uses 'main' branch, so there is no need to
specify that explicitly anymore.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/153"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> README: fix link used with 'west init'

- logging/log_backend_golioth.c
Timestamp is saved for raw mesages in logging v2, so send 'uptime', so
that cloud has that information as well.
Message index was correctly calculated, but actually never sent to
Golioth cloud. Start sending it now.
In case of logging v1 there was a possibility that log_msg_put()
was *not* called if an error occurred during processing. This resulted
in log message leak. Fix that.
In case of logging v1 and v2 message logging index was not incremented
in case of error, so make sure to do it correctly now.
Function name was never found, because colon (after "funcname:") was
never being search for in a proper buffer.
Make sure to first let cbprintf() be called, so that function name gets
propagated into the buffer and then search for colon in that buffer in
order to find function name.
> logging: v2 fixes and improvements

- logging/Kconfig
- logging/log_backend_golioth.c
QCBOR is already used in DFU mechanism, as it provides easier API for
parsing CBOR objects. Reimplement logging backend with QCBOR, so that
there is only single library used for CBOR encoding/decoding, allowing
to share more code between different device services.
Question is whether we want to make the switch now or wait a bit before
QCBOR proves to be the better library for other services (and samples)
as well.
TODO:
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/61"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> logging: golioth: use QCBOR instead of TinyCBOR

- samples/lightdb/observe/README.rst
- samples/lightdb/observe/src/main.c
So far '/observed' resource was used in this sample, while other samples
used '/counter' resource. Use the latter, so that the same 'goliothctl
...' commands can be used for multiple samples. This will hopefully
reduce confusion for user when switching back and forth from
'ligthdb/get' and 'lightdb/observe' samples.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: lightdb: observe: use '/counter' resource

- net/golioth/CMakeLists.txt
- net/golioth/coap_utils.c
- net/golioth/coap_utils.h
- net/golioth/fw.c
- net/golioth/golioth.c
Each path component (usually delimited by slash) should be encoded in
separate URI-Path option, instead of encoding whole path (includding
slashes) into single URI-Path.
Introduce coap_packet_append_uri_path_from_* helper functions:
- *_from_string_range - gets pointer to 'begin' and 'end' of string,
- *_from_string - gets pointer to string and its length,
- *_from_stringz - gets pointer to NULL-terminated string.
Replace previous invocations of coap_packet_append_option(packet,
COAP_OPTION_URI_PATH, ...) with above functions, so that path is
properly decomposed into multiple URI-Path CoAP options.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/161"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> net: golioth: fix decomposing path into URI-Path options

- samples/dfu/README.rst
- samples/hello/README.rst
- samples/hello_sporadic/README.rst
- samples/lightdb/get/README.rst
- samples/lightdb/observe/README.rst
- samples/lightdb/set/README.rst
- samples/lightdb_led/README.rst
- samples/lightdb_stream/README.rst
- samples/logging/README.rst
mcumgr flash commands were missing keywords and formatting
Signed-off-by: Mike Szczys <mike@golioth.io>
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: fix mcumgr commands

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
We were missing an easy way to file a feature request. The new forms add the ability to pick between filing a bug (with less mandatory fields) and filing a feature request.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> github: new Github feature request and bug report forms

- .github/workflows/build_test.yml
This will allow to further debug issues in CI, without having to run
twister locally.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> github: upload twister build logs and reports as artifacts

- .github/workflows/build_test.yml
Always upload twister artifacts, even in case of failure.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> github: always upload twister artifacts

- samples/hello/src/main.c
- samples/hello_sporadic/src/main.c
- samples/settings/src/main.c
Counter being incremented in a log call results in logging every third value. Moving the increment out fixes it.
Signed-off-by: Mike Szczys <mike@golioth.io>
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: hello: fix counter

- README.rst
- samples/dfu/README.rst
- samples/hello/README.rst
- samples/hello_sporadic/README.rst
- samples/lightdb/get/README.rst
- samples/lightdb/observe/README.rst
- samples/lightdb/set/README.rst
- samples/lightdb_led/README.rst
- samples/lightdb_stream/README.rst
- samples/logging/README.rst
- samples/settings/README.rst
So far links to 'latest' Zephyr RTOS documentation were used. All those
are broken at this moment except link to 'ESP32' board.
Update all of those (including ESP32 board link, for consistency) to
version 3.0.0 of Zephyr RTOS. Currently the recommended Zephyr RTOS
version (the one pointed to from `west.yml`) is somewhere between 2.7.0
and 3.0.0, so the latter is the best candidate as of now.
In future all links to Zephyr RTOS documentation (and any other
versioned documentation) need to be adjusted together with the component
version that is used.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Fixes: #181
> README: update links to Zephyr RTOS documentation to point to 3.0.0

- samples/hello_sporadic/sample.yaml
Both 'hello' and 'hello_sporadic' samples support the same set of
boards. Sync sample.yaml, so that all 'hello_sporadic' is build tested
for all boards.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: hello_sporadic: sync sample.yaml with hello sample

- samples/settings/CMakeLists.txt
- samples/settings/src/settings.c
In this PR we developed new command to the settings sample (get command) and included a '--json' flag to the shell commands (set/get) to print responses as json when setting or getting some setting.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> samples: settings: improve shell comands to set/get setting

- .editorconfig
Having support for editorconfig is convenient for SDK contributors, given that
it's supported by a large number of IDEs/editors, and the coding style
of Zephyr is a bit unique.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/186"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Create .editorconfig, copied from Zephyr

- README.rst
- west-ncs.yml
JIRA: https://golioth.atlassian.net/browse/DSDK-215
This is intended to be used in scenarios where our SDK is the manifest
repo, as described in NCS's Workflow 4:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_adding_code.html#workflow-4-application-as-the-manifest-repository
Previously, we were manually editing NCS's
west.yml to include the Golioth SDK, but this was manual and error-prone,
and it was too easy to select an invalid/non-working version of NCS.
Adding west-ncs.yml allows us to use NCS the same way we use vanilla
Zephyr for cases where the SDK is used as the manifest repo. The version
of NCS is pinned in this .yml, which avoids external users having to
manually select the NCS version, or add the Golioth SDK as a module in
NCS's west.yml.
Signed-off-by: …
> Add file west-ncs.yml, for using SDK as manifest repo with NCS

- .github/workflows/firebase-doxygen-main.yml
The job settings for the CI job that deploys docs live
on main were incorrectly set. The channelId and
FIREBASE_CLI_PREVIEWS were missing.
<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> .github: fix job settings for docs main deployment

- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .gitlab-ci.yml
- README.rst
- west-external.yml
- west-ncs.yml
- west-zephyr.yml
Add west-zephyr.yml root manifest for use cases when Golioth SDK is used
with vanilla Zephyr.
Add west-external.yml file with SDK-specific (not used by vanilla Zephyr
and/or NCS) dependencies, so that this file can be included from any
manifest file (either SDK's west-zephyr.yml, west-ncs.yml or standalone
application).
As a result there are 3 west manifest files provided in this repo:
* west-external.yml - generic manifest file specifying 'qcbor' library
as the only dependency (for now); this file is to be included by
standalone applications, which select their own version of Zephyr
RTOS and/or nRF Connect SDK,
* west-zephyr.yml - manifest file specifying Zephyr RTOS as dependency;
can be used as root west manifest (to try out samples/ with vanilla
Zephyr) or by standalone application …
> add west-zephyr.yml and simplify west.yml

- .gitlint
Initial gitlint configuration was generated based on old Zephyr .gitlint
file. Newest version specifies 75 line-length, which is in sync with
checkpatch and editorconfig tools. Update our .gitlint file to 75 line
lengths.
> gitlint: match max title length restriction with checkpatch

- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .gitlab-ci.yml
Newer 'west' version is needed (>= 0.12.0) in order to import NCS
successfully. Bump CI image now, so that 'west' does not need to be
overridden manually.
This updates Zephyr SDK version to 0.14.1
Remove manual configuration of ZEPHYR_SDK_INSTALL_DIR environment
variable from GitLab CI, as SDK is successfully found in CI image using
CMake package registry. Leave (and update) that environment variable in
GitHub Workflows, as GitHub CI uses different path as
$HOME (/github/home/ instead of /root/), which makes CMake package
registry (at /root/.cmake/) not visible.
> ci: update Zephyr CI image to v0.23.1

- .gitlab-ci.yml
So far NCS' west manifest file was patched in order to include Golioth
SDK as west module. Use 'west-ncs.yml', so that west workspace
initialization is simplified and the correct version is not hardcoded
into CI script.
Depends on (and contains commits from): #201
> gitlab-ci: use west-ncs.yml for 'twister-ncs' job

- samples/settings/prj.conf
The settings sample needs to be able to reboot via shell
after setting WiFi and Golioth credentials, so
CONFIG_REBOOT is required to enable the "kernel reboot cold/warm"
commands.
> settings: enable CONFIG_REBOOT

- samples/settings/README.rst
This is a leftover from nRF91 Feather and Thingy:91. In case of DK, there
is no bootloader mode.
> samples: settings: remove comment about bootloader mode for nRF91 DK

- west-zephyr.yml
ST hal libraries were added as there was work in progress that was adding
STM32 platforms support to samples. This won't happen in the close future
however, so remove unused HAL libraries.
> west-zephyr: remove unused ST hal

- samples/dfu/boards/nrf52840dk_nrf52840.overlay
- samples/dfu/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello/boards/nrf52840dk_nrf52840.overlay
- samples/hello/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello_sporadic/boards/nrf52840dk_nrf52840.overlay
- samples/hello_sporadic/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/get/boards/nrf52840dk_nrf52840.overlay
- samples/lightdb/get/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/observe/boards/nrf52840dk_nrf52840.overlay
- samples/lightdb/observe/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/set/boards/nrf52840dk_nrf52840.overlay
- samples/lightdb/set/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_led/boards/nrf52840dk_nrf52840.overlay
- samples/lightdb_led/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_led/src/main.c
- samples/lightdb_stream/boards/nrf52840dk_nrf52840.overlay
- samples/lightdb_stream/boards/nrf9160dk_nrf9160_ns.conf
- samples/logging/boards/nrf52840dk_nrf52840.overlay
- samples/logging/boards/nrf9160dk_nrf9160_ns.conf
- samples/settings/boards/nrf52840dk_nrf52840.overlay
- samples/settings/boards/nrf9160dk_nrf9160_ns.conf
- west-ncs.yml
- west-zephyr.yml
After commit "lib: nrf_modem: don't enforce socket priority over native
TLS" was merged into 'main' branch of NCS it is possible to configure priority
of Zephyr TLS implementation to be higher than offloaded nRF9160 TLS.
This makes it possible to select Zephyr TLS (mbedTLS) implementation at
build time, which was not possible from NCS 1.8.0.
In case of Zephyr there are numerous networking stack and esp-at driver 
bugfixes in main branch.
Resolves: #158
Closes: #190 #193
> bump Zephyr and NCS to tip of main

- docs/README.md
Docs are now deployed to zephyr-sdk-docs.golioth.io when
PRs merge to main.
> docs: update URL of deployed doxygen site

- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .gitlab-ci.yml
This updates Zephyr SDK version to 0.14.2.
Remove also `west espressif install` from GitLab CI, as it is no longer needed.
> ci: update Zephyr CI image to v0.23.3

- net/golioth/golioth.c
This is the last inconsistent place where zsock_ prefix was not used. Add
it there, so now samples can be successfully built with CONFIG_POSIX_API=y.
> net: golioth: use zsock_ prefix with addrinfo

- net/golioth/golioth.c
Return code was saved to 'ret' variable, but 'err' variable was checked in
the next like instead.
In fact number of sent bytes should be compared with the number returned
from underlying zsock_send() call. Do exactly that inside
golioth_sendmsg(), as that function contains number of total bytes that
should be sent. Change golioth_sendmsg() behavior to return 0 in case of
success and negative value in case of error.
Save value returned from golioth_sendmsg() to 'err', which by convention
can be 0 (success) or negative (error).
Reported-by: Nick Miller <nick@golioth.io>
> net: golioth: fix golioth_sendmsg() return code check

- net/golioth/golioth.c
Both golioth_send() and golioth_sendmsg() use __golioth_send().
__golioth_send() already converts zsock_send() error codes from:
* -1 (with errno) - in case of error
* number of bytes sent - in case of success
into:
* -errno - in case of zsock_send() error
* 0 - in case of success
Similar logic was implemented in golioth_sendmsg(). Additionally
golioth_sendmsg() checks now for number of bytes actually sent, so that
truncated datagrams can be detected, in which case -EIO is returned. This
behavior is wrong, as __golioth_send() never returns positive values, so
golioth_sendmsg() always ends up returning -EIO.
Fix above issue by moving the check for truncated packets into
__golioth_send() function. It will now return following values:
* -errno - in case of zsock_send() error
* -EIO - in case …
> net: golioth: fix golioth_send{,msg}() error path (again)

- logging/log_backend_golioth.c
When "autostart" argument is "true" in LOG_BACKEND_DEFINE() invocation,
then log_backend_enable() is called automatically during system boot. In
case of Golioth backend autostart is disabled due to dependency on Golioth
client instance initialization in application code.
log_backend_activate() was called so far in order to "plug in" Golioth
logging backend. However this does just part of the job of
log_backend_enable(), because it does not assign log id and setup log
filters. Those are required in order to make log filtering work for Golioth
backend.
Fix Golioth logging backend initialization (which includes log filtering
capabilities) by calling log_backend_enable() instead of
log_backend_activate().
Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>
> logging: fix Golioth backend registration

- samples/dfu/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello_sporadic/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/get/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/observe/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/set/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_led/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_stream/boards/nrf9160dk_nrf9160_ns.conf
- samples/logging/boards/nrf9160dk_nrf9160_ns.conf
- samples/settings/boards/nrf9160dk_nrf9160_ns.conf
- west-ncs.yml
- west-zephyr.yml
Both are the latest stable releases.
> west: bump Zephyr to 3.1.0 and NCS to 2.0.0

- net/golioth/Kconfig
- net/golioth/system_client.c
So far system client priority was hardcoded to the lowest application
priority. Introduce a Kconfig option that defaults to the same, but allows
to configure it per application needs.
> net: golioth: system_client: add Kconfig configurable thread priority

- include/net/golioth.h
- net/golioth/golioth.c
As per `connect(3)` manpages:
```
The connect() function shall attempt to make a connection on a
connection-mode socket or to set or reset the peer address of a
connectionless-mode socket.
```
and:
```
If the initiating socket is connection-mode, then connect() shall attempt
to establish a connection to the address specified by the address
argument. If the connection cannot be established immediately and
O_NONBLOCK is not set for the file descriptor for the socket, connect()
shall block for up to an unspecified timeout interval until the
connection is established.
```
RFC 6347 (DTLS 1.2) interchangably uses the terms association, session and
connection. Though it is not specified in neither POSIX nor Zephyr how DTLS
sockets should be treated (they are really just Zephyr extension), it …
> enforce DTLS handshake in golioth_connect() and add golioth_is_connected()

- west-zephyr.yml
ESP32 platform had broken chain-loading of application image at least
starting from Zephyr 2.7.0 stable release and it was still not fixed with
the release of 3.1.0.
In fact the problem is in MCUboot bootloader, but it is Zephyr which
decides what version of MCUboot is pulled in.
Change revision of MCUboot that is used with west-zephyr.yml manifest file
to a version that contains a fix for ESP32 application chain-loading.
Fortunately used revision contains only this single fix (compared to
revision pulled in by Zephyr 3.1.0), so there is no risk of breaking other
functionalities/platforms.
Split from #227
> west-zephyr: bump MCUboot to include fix for ESP32

- samples/lightdb_led/src/main.c
While loop is expected to run until "no more items" condition is reached.
Clear that decoding error, so that further processing can rely on
QCBOR_SUCCESS code.
Fixes: #220
> samples: lightdb_led: reset QCBOR error after "no more items"

- net/golioth/Kconfig
- net/golioth/system_client.c
So far 1 was used as TLS credentials tag. This was copy-pasted from Zephyr
TLS sample code and most likely would conflict with user code trying to
maintain second TLS connection together with connection with Golioth cloud.
Add configurable option, so that application can decide which tag to use
when managing connection by Golioth system client. Also choose a random
number, so that chances of conflict are minimized.
> net: golioth: system_client: add configurable TLS credentials tag

- samples/settings/Kconfig
- samples/settings/README.rst
The instructions in the current samples/settings README
are incorrect for ESP32. They indicate that the user should
set CONFIG_ESP32_WIFI_SSID and CONFIG_ESP32_WIFI_PSK, but
when setting these, the project will not build.
To fix, use CONFIG_GOLIOTH_SAMPLE_WIFI_SSID/PSK instead,
similar to the other samples.
> settings: fix ESP32 WiFi credentials

- include/net/golioth/rpc.h
- include/net/golioth/settings.h
Currently both RPC and Settings headers pull QCBOR headers. This means that
QCBOR module needs to be added as Zephyr module (e.g. by specifying in west
manifest when west is used for repository management). This is true even
when neither RPC nor Settings are actually used (like it is the case for
simplest 'hello' sample).
Remove QCBOR header inclusion and forward declare QCBORDecodeContext and
QCBOREncodeContext types instead. As pointers to those types are used in
the Golioth RPC/Settings APIs, then there is no need to have full
information about those types as long as their values are not referenced.
This solves build errors of samples that do not use RPC and Settings and do
not enable CONFIG_QCBOR.
> golioth: {rpc,settings}: forward declare qcbor typedefs and drop header use

- include/net/golioth.h
- net/golioth/golioth.c
- net/golioth/system_client.c
Initial version of SDK supported both DTLS (ciphertext) and
UDP (plaintext), which was handy for low level debugging with self-hosted
server. This is however not used anymore and probably not working anymore.
Drop plaintext/unsecure UDP, which is not supported/tested anymore.
> net: golioth: drop support for plaintext/unsecure UDP

- net/golioth/settings.c
The prior assertion assumed the setting label was
always type QCBOR_TYPE_BYTE_STRING.
However, when testing settings, there was a board crash
due to detecting the label as type QCBOR_TYPE_TEXT_STRING.
Updating the assertion to allow either type for the label.
> settings: allow label type as byte or text string

- samples/dfu/sample.yaml
- samples/hello/sample.yaml
- samples/hello_sporadic/sample.yaml
- samples/lightdb/get/sample.yaml
- samples/lightdb/observe/sample.yaml
- samples/lightdb/set/sample.yaml
- samples/lightdb_led/sample.yaml
- samples/lightdb_stream/sample.yaml
- samples/logging/sample.yaml
- samples/settings/sample.yaml
twister filters out ESP32 platforms from all samples, because they have
'net' tag specified, which is excluded in 'esp32' board definition in
Zephyr. This is the case after ESP32 platform got support in Zephyr SDK.
Fixes: 12b34cc201e0 ("bump Zephyr and NCS to tip of main")
> samples: remove 'net' tag from all sample.yaml

- net/golioth/Kconfig
- net/golioth/rpc.c
- net/golioth/settings.c
- samples/rpc/src/main.c
There were build failures in samples when both RPC and Settings were enabled, so these commits fix those issues.
> RPC and Settings Build Fixes

- include/net/golioth/settings.h
- net/golioth/settings.c
- samples/settings/src/main.c
The backend now supports CBOR encoding of integers.
Add additional type for int64 settings.
CBOR-encoded integers only use as many bytes as
necessary, but we will treat them all as uint64_t
after decoding.
Note: The Golioth backend does not support
integers greater than INT64_MAX (9223372036854775807),
so there's no need to support a uint64 type.
Tested with local backend and local UI on branches with CBOR-encoding fixes:
Backend: https://github.com/golioth/golioth/pull/168
UI: https://github.com/golioth/golioth-web/pull/49
> golioth_settings: add int64 support

- net/golioth/golioth.c
If CONFIG_LOG_GOLIOTH_LOG_LEVEL_DBG is set to 'y'
then the system will freeze at boot after a couple
of seconds (tested on nRF9160dk), which I suspect
is due to the hexdump of tx packets, because when
the hexdump is removed, the system boots normally.
> net/golioth: remove hexdump of tx packet

- include/net/golioth.h
- net/golioth/golioth.c
- samples/lightdb/get/src/main.c
- samples/lightdb/observe/src/main.c
- samples/lightdb/set/src/main.c
- samples/lightdb_led/src/main.c
- samples/lightdb_stream/src/main.c
Remove use of `text/plain` content format in favor of `application/json`.
Introduce `enum golioth_content_format` and use it in public lightdb APIs. This is the first step in phasing out explicit use of CoAP in public (high-level) APIs.
> Content format cleanups and introduction of golioth_content_format

- net/golioth/coap_utils.c
- net/golioth/coap_utils.h
- net/golioth/golioth.c
There are few coap_data_* APIs, which handle low-level CoAP packet parsing.
Move them to coap_utils.c, which is a perfect fit for those.
> golioth: move coap_data_* helpers to coap_utils.c

- samples/hello/src/main.c
- samples/hello_sporadic/src/main.c
- samples/lightdb/get/src/main.c
- samples/lightdb/set/src/main.c
- samples/lightdb_stream/src/main.c
- samples/logging/src/main.c
Add semaphore to samples, which will be released after connecting to cloud. That way first request to Golioth cloud will likely succeed, giving a better user experience.
> samples: wait for valid connection before first request

- net/golioth/settings.c
- samples/settings/src/main.c
* settings: send response as CBOR
* samples/settings: LOOP_DELAY_S is int64 instead of float 
---
~(Aug 16, 2022) Leaving this as a Draft PR for now, until support on the backend is deployed to production, at which point I'll turn it into a proper PR.~
(Aug 25, 2022) Backend support for CBOR types and `.c/status` is deployed, so marking PR as "Ready for review"
> settings: send response as CBOR

- .gitlab-ci.yml
This option was introduced with commit 46484fbe6ce1 ("gitlab-ci: add
thingy91_nrf9160_ns tests with NCS"). Unfortunately this line was not
removed with removal of thingy91 board in commit 72b1bcf52778 ("limit
supported platforms to ESP32, nRF52840DK, nRF9160DK and QEMU_x86"), so do
it now.
> gitlab-ci: remove --board-root option

- samples/dfu/src/main.c
So far sys_reboot() was called directly from CoAP reply callback after a
bit of delay. This was fine so far, as all packets sent to cloud with
golioth_fw_report_state() were sent synchronously (just once, without
waiting for reply or acknowledgement). This approach prevents any
communication with Golioth cloud, as connection thread (the one calling
data_received() callback) is blocked. This means that no packet (for
reporting firmware version) retransmission is possible (once it will be
implemented).
Get rid of k_sleep() call and schedule a work item that will be run from
system workqueue with proper delay. That way Golioth CoAP receive handler
is not blocked and communication with Golioth cloud can still happen,
leaving possibility for sending CoAP request from golioth_fw_report_state() …
> samples: dfu: call sys_reboot() from sysworkq

- net/golioth/golioth.c
- net/golioth/rpc.c
- net/golioth/settings.c
We should not return -1 directly. Instead, POSIX error code should be returned, so there is same developer experience for most APIs.
> {rpc,settings}: use POSIX error codes instead of -1

- samples/lightdb_led/README.rst
- samples/lightdb_led/src/main.c
This message is mentioned as part of README.rst and is very useful for
verifying if LED values are received correctly. This is especially
important for qemu_x86.
This brings back behavior before commit f72c094fe1f3 ("samples:
lightdb_led: convert from TinyCBOR to QCBOR") was merged.
> samples: lightdb_led: bring back "LED <num> -> <value>" info log

- .github/disabled_workflows/test_nrf9160dk.yml
- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .github/workflows/gitlint.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test_mimxrt1060.yml
- .github/workflows/test_nrf52840dk.yml
Removed the constraint "branches: [main]" so that CI workflows will run even for pull requests that are based on branches other than main.
> .github: enable workflows on every PR

- net/golioth/Kconfig
Support for plaintext UDP has been removed with commit e316e566d6c2 ("net: golioth: drop support for plaintext/unsecure UDP"), so remove setting default UDP port to 5683.
> golioth: always default to port 5684

- samples/common/settings_shell.c
So far there was no consistence around using:
* shell_error(...) vs
* shell_fprintf(..., SHELL_ERROR, ...) vs
* shell_fprintf(..., SHELL_VT100_COLOR_RED, ...)
as well as with:
* shell_print(...) vs
* shell_fprintf(..., SHELL_NORMAL, ...) vs
* shell_fprintf(..., SHELL_VT100_COLOR_GREEN, ...)
Unify those and always use shell_error() in the first case and
shell_print() in the latter case. Note that this changes color of some
printed strings from green to default (white/grey), but this was done on
purpose (to improve consistency of printed strings across other Zephyr
shell commands, that also use default font color in most cases).
Change also single invocation of shell_fprintf(..., SHELL_WARNING, ...) to
shell_warn().
Introduce helpers that allow to deduplicate some boilerplate related to …
> samples: common: deduplicate json/plain status printing

- net/golioth/fw.c
- samples/dfu/src/main.c
So far those log messages were printed when there were no dfu releases rolled out yet:
```
<err> golioth: Failed to get manifest bstr: 34 (QCBOR_ERR_LABEL_NOT_FOUND)
<err> golioth_dfu: Failed to parse desired version: -13
```
Handle the case when sequence-number is not found in CBOR map and return -ENOENT to signal no "desired version". Handle that in samples/dfu/ application, so that following log messages are printed instead:
```
<inf> golioth_dfu: No release rolled out yet
```
> fw: gracefully handle case when no releases were rolled out yet

- .github/workflows/test_mimxrt1060.yml
Ensure correct J-Link is used by specify in serial number in runner_env.sh
> workflows: add serial number for mimxrt1060_evkb

- samples/hello/boards/esp32.overlay
Add missing overlay file that enabled WiFi node.
Fixes: d9860924182b ("bump Zephyr to tip of main (post 3.2.0-rc2)")
> samples: hello: add missing 'esp32' overlay

- samples/dfu/boards/qemu_x86.conf
s/There is not/There is no/ in comment about CONFIG_SETTINGS=n.
> samples: dfu: fix typo in qemu_x86 configuration

- samples/dfu/README.rst
DFU sample requires to use `settings` shell commands in order to setup WiFi credentials. Update README accordingly.
> samples: dfu: remove ESP32 specific section about WiFi credentials

- samples/dfu/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello_sporadic/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/get/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/observe/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/set/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_led/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_stream/boards/nrf9160dk_nrf9160_ns.conf
- samples/logging/boards/nrf9160dk_nrf9160_ns.conf
- samples/rpc/boards/nrf9160dk_nrf9160_ns.conf
- samples/settings/boards/nrf9160dk_nrf9160_ns.conf
- samples/test/boards/nrf9160dk_nrf9160_ns.conf
- west-ncs.yml
NRF_SECURITY module in NCS is enabled by default and we probably want to
keep it enabled, so that existing NCS users are not restricted by Golioth
SDK (e.g. by forcing NRF_SECURITY to be disabled). This module seems to
dropped old/legacy SPM module and now uses something new, which pulls in
NCS fork of mbedTLS as a dependency. This is expressed by 'select
DISABLE_MBEDTLS_BUILTIN if MBEDTLS' in both NRF_SECURITY and
NRF_SECURITY_BACKEND Kconfig options.
Using NCS fork of mbedTLS means selecting
CONFIG_MBEDTLS_TLS_LIBRARY (CONFIG_MBEDTLS_TLS_LIBRARY is NCS fork,
CONFIG_MBEDTLS_BUILTIN is Zephyr fork of mbedTLS).
NCS fork (as compared to Zephyr fork) of mbedTLS has set of Kconfig options
that are named differently (like CONFIG_MBEDTLS_SSL_PROTO_DTLS in NCS vs
CONFIG_MBEDTLS_DTLS in Zephyr), …
> bump NCS to v2.1.0

- .github/workflows/build_test.yml
- .gitlab-ci.yml
Today ESP32 platform is supported by Zephyr SDK and the only distinct thing
about this platform is the need for downloading binary blobs. Those blobs
are downloaded now with Zephyr upstream feature called `west blobs`.
Just merge `twister-esp` GitLab CI job into `twister` for code deduplication.
For GitHub CI add `esp32` platform to twister invocation. This is making 
(non NCS) twister build-only tests in GitHub Actionn equivalent to GitLab CI.
> ci: add 'esp32' platform build tests with twister

- net/CMakeLists.txt
- net/Kconfig
- net/golioth/Kconfig
- net/golioth/system_client.c
- net/sockets/CMakeLists.txt
- net/sockets/Kconfig
- net/sockets/sockets_offload_poll_wrapper.c
- samples/dfu/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello/boards/nrf9160dk_nrf9160_ns.conf
- samples/hello_sporadic/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/get/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/observe/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb/set/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_led/boards/nrf9160dk_nrf9160_ns.conf
- samples/lightdb_stream/boards/nrf9160dk_nrf9160_ns.conf
- samples/logging/boards/nrf9160dk_nrf9160_ns.conf
- samples/rpc/boards/nrf9160dk_nrf9160_ns.conf
- samples/settings/boards/nrf9160dk_nrf9160_ns.conf
- samples/test/boards/nrf9160dk_nrf9160_ns.conf
There is a special ZFD_IOCTL_POLL_OFFLOAD ioctl() request used inside
poll() system call handling, which allows to offload whole poll() system
call to driver offloading sockets operations (like NCS' nRF91 sockets
driver). Offloading whole poll() execution doesn't allow to use Zephyr
native sockets (either from another network driver or just software
concepts like socketpair and eventfd). This is a huge restriction, because
it prevents "interrupting" poll() system call and blocks thread calling
poll() until new data arrives (at least when using POLLIN event).
Introduce offloaded sockets wrapper, which wraps all socket operations with
special behavior added specifically in poll() system call handling.
ZFD_IOCTL_POLL_PREPARE ioctl() request is handled (instead of returning
-EXDEV by …
> sockets_offload_poll_wrapper: introduce new module and use it by nRF91

- include/net/golioth.h
- include/net/golioth/req.h
- net/golioth/CMakeLists.txt
- net/golioth/coap_req.c
- net/golioth/coap_req.h
- net/golioth/coap_utils.h
- net/golioth/golioth.c
- net/golioth/golioth_utils.c
- net/golioth/golioth_utils.h
- net/golioth/system_client.c
Introduce new helper module, which will handle most low-level CoAP specific
tasks like:
* contructing CoAP packets for the most common use cases,
* keeping track of pending (unacked) CoAP packets,
* retransmitting packets with exponential backoff,
* requesting wakeup from poll() system call, when new packet is to be
transmitted or there is a retransmission of pending packet needed,
* handling block-wise transfers (requesting next blocks of data, if
response contains information about block number),
* providing thread-safe APIs.
Add `golioth_prepare_poll()` function will allow to get file descriptor and next
timeout value, so those values can be passed to subsequent poll() system call. 
This is used by `system_client.c` implementation, but the idea is to split it into 
application specific …
> [CoAP rework] coap_req: introduce new helper module

- samples/common/wifi.c
So far only CONNECT_RESULT wifi_mgmt event was handled. This should be
enough with properly functioning WiFi drivers, which should use that event
for either succeeded or failed connect attempt (status code is always
passed with CONNECT_RESULT, which defines whether it was a success or
failure). However current implementation of ESP32 WiFi driver seems to not
respect wifi_mgmt APIs and sends DISCONNECT_RESULT wifi_mgmt result on
failed connect attempt.
Handle DISCONNECT_RESULT events and treat that as if CONNECT_RESULT was
received with -EFAULT status code was received. This workarounds current
ESP32 WiFi driver implementation. This driver needs to be fixed anyway, but
more drivers might appear in the future with such broken behavior.
So far there was fixed 5s interval between subsequent …
> samples: common: wifi: handle DISCONNECT_RESULT wifi_mgmt event and change retry interval

- net/golioth/coap_req.c
- net/golioth/coap_req.h
Previously, the cb parameter of golioth_coap_req_cb was required. If it was set to NULL, the system would crash due to NULL dereference.
There have been a couple of instances of crashes which were due to this behavior. In one case, it was inadvertant (user meant to set a callback, but forgot). In the other case, it was intentional (rpc.c and settings.c both set the callback to NULL when sending the response, because they don't care about the response).
It seems like the most reasonable thing to do is to allow for a NULL callback, since there are legitimate requests that don't care to be called back ("fire and forget").
For cases where setting a NULL callback is unintentional, the user will be alerted soon enough when they realize that nothing is happening in response to their request …
> coap_req: allow NULL callback

- net/golioth/rpc.c
- net/golioth/settings.c
Just replace `enum coap_content_format` with `enum golioth_content_format`
equivalents.
> {settings,rpc}: use 'enum golioth_content_format'

- net/golioth/coap_req.c
- net/golioth/golioth_utils.c
- net/golioth/golioth_utils.h
- net/golioth/rpc.c
- net/golioth/settings.c
Replace static default_req_cb() with a golioth_req_rsp_default_handler() that produces error/debug messages on received response. Especially error messages are useful in case of CoAP ACK timeout or non-2 (non-success) CoAP response code class.
Add additional "hidden" (not documented to SDK consumers) functionality about logging additional module/component information string, so that it is easier to locate source component from specific log comes from. As an example for settings.c this is what will appear in Zephyr console:
```
<dbg> golioth: Settings response ACK
73 65 74 74 69 6e 67 73  20 73 79 6e 63 65 64  |settings  synced
```
as a result of successful acknowledgment, when debug logs are enabled.
Make this function private to SDK internal implementation, so that above experimental …
> golioth: add golioth_req_rsp_default_handler() default response handler

- .gitlab-ci.yml
GitLab CI handles color escape sequences without any issues, however automatic detection does not work due to output stream of running commands not being a tty.
Add --force-color, so that twister output will be colorized.
> gitlab-ci: add --force-color to twister invocation

- samples/lightdb/delete/pytest/test_sample.py
- samples/lightdb/get/pytest/test_sample.py
- samples/lightdb/observe/pytest/test_sample.py
- samples/lightdb/set/pytest/test_sample.py
- samples/lightdb_led/pytest/test_sample.py
- samples/lightdb_stream/pytest/test_sample.py
- samples/logging/pytest/test_sample.py
All samples but DFU are not handlng properly the case when
--initial-timeout is not provided (which is true for all platforms other
than nRF91). request.config.getoption('--initial-timeout', DEFAULT_TIMEOUT)
retured None, which means that None was passed to pexpect.expect() or
pexpect.readline() methods. This was resulting in infinite timeouts,
instead of default 30s timeouts.
Copy initial_timeout fixture from DFU's pytest script to all other samples'
scripts.
Remove dead code in lightdb/observe pytest script.
Fix lightdb/get pytest script to handle counter values logged as hexdump. 
See commit message for details why this was not detected in CI (and why
other bugs might be missed as well).
> samples: pytest: improvements and fixes

- net/golioth/fw.c
- samples/dfu/src/main.c
So far there were 3 threads involved:
* Zephyr main
* initialize network
* start Golioth system client
* Golioth system_client
* handle incoming Golioth communication
* report FW states
* Zephyr sysworkq
* trigger reboot
This is overly complicated and makes callbacks implementation hard to read
due to FW state reporting logic taking most of callback body.
Change implementation to utilize only 2 threads instead, with following
changes:
* Zephyr main
* initialize network (as before)
* start Golioth system client (as before)
* report FW reporting (new)
* trigger reboot (new)
* Golioth system_client
* handle incoming Golioth communication
There is little data shared among those threads and most important thing
is to notify about state of FW download. For that reason use
semaphores, which make …
> samples: dfu: report FW state and reboot from main thread

- samples/lightdb/delete/boards/esp32.overlay
This is needed to get WiFi working with ESP32 board.
> samples: lightdb: delete: add missing esp32.overlay

- .github/disabled_workflows/test_mimxrt1060.yml
- .github/disabled_workflows/test_nrf9160dk.yml
- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .github/workflows/firebase-doxygen-main.yml
- .github/workflows/firebase-doxygen-pr.yml
- .github/workflows/gitlint.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test_nrf52840dk.yml
This suppresses following warning:
> Node.js 12 actions are deprecated.
> github-ci: update to actions/checkout@v3

- net/golioth/coap_req.c
- net/golioth/coap_req.h
As per CoAP OBSERVE RFC7641 section "4.4. Reordering", server can choose
any arbitrary number as initial sequence number as OBSERVE CoAP option
value. In paticular, local clock can be used to generate sequence numbers,
so that specific sequence number values do not need to be remembered on
server side.
In order to handle that successfully, client needs to implement timestamp
comparison as per RFC7641 section "3.4. Reordering". So far only sequence
number comparison was used, so add missing timestamp comparison to be
compliant with CoAP OBSERVE spec and handle newest Golioth backend
behavior.
While at it, change wording of 'age' to 'seq' and/or 'sequence number', so
it will match what is used in RFC7641 specification.
> coap_req: add timestamp comparison to OBSERVE notifications

- net/golioth/coap_req.h
`golioth_coap_reqs_poll_prepare()` does not get `req` as parameter, but
`client` instead. Fix doxygen docs that say otherwise.
> coap_req: fix golioth_coap_reqs_poll_prepare() docs

- net/sockets/sockets_offload_poll_wrapper.c
So far there was a possibility that work item was in both RUNNING and
QUEUED states. As a result of `zsock_close()` call, threaded (executed from
workqueue) `zsock_poll()` returned. However just because work was QUEUED,
`sock_wrapper_poll_handler()` was entered once again by workqueue thread.
Subsequent work cancellation with `k_work_cancel_sync()` could no longer be
finished, as work was waiting once again on `zsock_close()`.
Start work cancellation using `k_work_cancel()` just before `zsock_close()`
is invoked. This clears QUEUED state from work item, so
`sock_wrapper_poll_handler()` is not reentered. After `zsock_close()` has
returned, it is safe to call `k_work_cancel_sync()` to finish work
cancellation and make sure that `sock_wrapper_poll_handler()` (hence
`zsock_poll()`) is no …
> sockets_offload_poll_wrapper: cancel work before socket close

- tests/lightdb/src/main.c
This test does not expect any counter, so remove this word from log
message.
If there was an error during asynchronous (callback-based) request, then
such error was not propagated to `struct async_data` structure, but instead
it was still set to `0`, just like the API would be successful. Later, test
would discover a problem anyway, as received data would not match with
expected one. However, it is better to propagate error and not rely on data
comparison.
> tests: lightdb: fix error handling and fix copy-paste error in log

- net/golioth/Kconfig
- net/golioth/settings.c
Before this change, the max length of the settings response was fixed at 256 (#define'd in the source code of settings.c). This was problematic for devices with many settings, because if there are multiple errors encountered while handling the settings, the response length becomes too large to fit in the response buffer, resulting in a QCBOR error:
QCBOREncode_FinishGetSize error: 1 (QCBOR_ERR_BUFFER_TOO_SMALL)
To accomodate users with lots of settings, make the response length configurable via Kconfig.
The recommendation of 50 * N for the max length is given because each error encountered results in a CBOR entry like:
{ "setting_key": string, "error_code": int }
The "setting_key" and "error_code" strings alone account for 21 bytes, then if you add in the name of the setting (string) and …
> Kconfig: add GOLIOTH_SETTINGS_MAX_RESPONSE_LEN

- net/golioth/coap_req.c
Poorly formatted JSON is a common cause for errors when using LightDB State/Stream. This commit watches for the -EFAULT error code and publishes a warning to check the formatting.
> net: add log message for invalid format

- net/golioth/system_client.c
There is a race condition between getting connected and actually flushing
eventfd. If some event (like scheduling new packets from
`client->on_connect()` callback) occurred in between, then such event would
be ignored.
Flush pending events notification in eventfd before attempting connect, so
no events get discarded after connection was established.
Following flow triggers unwanted reconnection when using settings as a
source of Golioth credentials:
- Initializing Zephyr settings subsystem
- Configuring Golioth credentials + setting `FLAG_RECONNECT` bit in `flags`
atomic variable
- Starting system client thread
- Getting successfully connected by system client
- Clearing eventfd (to flush any reconnect, timeout and outgoing traffic
requests)
- Waiting for incoming communication or eventfd …
> system_client: fix flushing of events before connect attempt

- CHANGELOG.md
- include/net/golioth.h
- include/net/golioth/rpc.h
- include/net/golioth/settings.h
- net/golioth/rpc.c
- net/golioth/settings.c
- net/golioth/system_client.c
- samples/rpc/src/main.c
- samples/settings/src/main.c
Currently, when golioth_rpc_register() is called, an observation is automatically established (if it’s the first RPC method being registered).
Similarly, when golioth_settings_register_callback() is called, an observation is automatically established.
However, this “automatic observe” behavior has three main issues:
1. It might be unwanted in some user applications (e.g. low-power/low-data) that don’t want the overhead of observations
2. It’s inconsistent with the way observations work for DFU. For DFU, it’s expected that the user calls golioth_fw_observe_desired() in the on_connect callback (i.e. observations are not automatically established).
3. It can be unexpected/surprising that an API named “register callback” would also create an observation.
We should separate RPC and Settings …
> rpc, settings: remove automatic observations

- .github/disabled_workflows/test_mimxrt1060.yml
- .github/disabled_workflows/test_nrf9160dk.yml
- .github/workflows/test_nrf52840dk.yml
* The .yml file should have been named `credentials_nrf{52840,9160}dk.yml`
* The format of the settings is YAML, not JSON
> .github: fix documentation errors

- net/golioth/golioth.c
`zsock_setsockopt()` expects to receive `NULL` terminated string and length of
the string **including** `NULL` termination. Adjust code to follow that.
See Zephyr upstream commit 4234e801b544 ("net: sockets: Fix TLS_HOSTNAME
option length inconsistency") for details.
> golioth: fix zsock_setsockopt(..., TLS_HOSTNAME, ...) API use

- net/sockets/Kconfig
- west-ncs.yml
Update to the latest release candidate to keep track of the upstream
improvements and changes.
> bump NCS to 2.3.0

- samples/common/Kconfig
This was referenced, but never used. Remove it.
> samples: common: remove GOLIOTH_SAMPLE_INCLUDE_HEADERS

- .ci-west-zephyr.yml
- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .github/workflows/test_nrf52840dk.yml
- .gitlab-ci.yml
- west-zephyr.yml
In case of `west-zephyr.yml` there is a name-allowlist filter, while in case
of `west-ncs.yml` there is no such filter. This makes filtering logic
inconsistent across Zephyr vanilla vs NCS.
Limiting repositories has a major flaw when user wants to utilize a generic
library such as picolibc, which is filtered out. In that case it is needed
to add that repository to downstream manifest or temporarily modify
`west-zephyr.yml` in order to test some non-standard configuration with SDK
samples.
Let's be consistent about Zephyr modules filtering and always import all
the modules in `west-zephyr.yml`, just like it happens with `west-ncs.yml`.
Since limiting `west-zephyr.yml` was mainly a clone time improvement,
noticeable in CI, add .ci-`west-zephyr.yml` which will limit repositories
just for …
> west-zephyr: import all Zephyr modules

- samples/rpc/src/main.c
Right now this sample was silent on the Zephyr console, so the only way to
tell whether RPC was executed was using REST API and/or web console. This
however does not tell whether tested board was the one responding with
correct results.
Add debug logs, so that every RPC invocation results in clear notification
on Zephyr console.
> samples: rpc: log during method invocations

- net/golioth/coap_req.c
Use `%zu` instead of `%d` for printing `size_t new_offset` variable. This
suppresses build time warnings for `qemu_x86_64` platform:
```
coap_req.c:257:33: warning: format '%d' expects argument of type 'int', \
but argument 2 has type 'size_t' {aka 'long unsigned int'} [-Wformat=]
```
> coap_req: fix log format for 'size_t'

- include/net/golioth.h
- net/golioth/Kconfig
- net/golioth/golioth.c
This member was never used. Since `coap_packet_parse()` handles passing `NULL`
pointer, use that instead of storing received CoAP options.
> golioth: remove 'client->rx_options'

- .github/workflows/build_test.yml
- .github/workflows/checkpatch.yml
- .github/workflows/test_nrf52840dk.yml
- .gitlab-ci.yml
This updates Zephyr SDK version to 0.16.0.
> ci: update Zephyr CI image to v0.26.1

- scripts/python/golioth/golioth/__init__.py
- scripts/python/golioth/golioth/cli.py
- scripts/python/golioth/golioth/golioth.py
There are various new CLI commands implemented:
* `golioth artifacts upload -rrf build/zephyr/zephyr.bin`
All in one go:
- automatically figure out version from MCUboot signature metadata (from `zephyr.signed.bin`
images)
- upload an artifact with this version
- create a release with version as a release-tag (first `-r` flag)
- rollout firmware (second `-r` flag)
- remove any conflicting artifacts/releases (with the same version/release-tag) if they were
previously existing (`-f` flag)
* `golioth artifacts delete '*'`
Delete all artifacts.
* `golioth artifacts list`
List all artifacts.
* `golioth releases delete '*'`
Delete all releases.
* `golioth releases list`
List all releases.
* `golioth lightdb monitor -d DEVICE_NAME /counter`
Monitor `/counter` in LightDB State
* `golioth stream …
> scripts: python: DFU (Artifacts/Release) + State/Stream Monitoring

- README.rst
- samples/dfu/README.rst
- samples/hello/README.rst
- samples/hello_sporadic/README.rst
- samples/lightdb/delete/README.rst
- samples/lightdb/get/README.rst
- samples/lightdb/observe/README.rst
- samples/lightdb/set/README.rst
- samples/lightdb_led/README.rst
- samples/lightdb_stream/README.rst
- samples/logging/README.rst
- tests/lightdb/README.rst
All links were pointing to Zephyr 3.0.0. Since we support Zephyr 3.3.0,
provide links to that version of docs.
> docs: update all links to Zephyr docs to v3.3.0

- README.rst
Since DK is the continuously verified board instead Feather, reference the
former in README file.
> README: reference nRF9160 DK instead of nRF9160 Feather

- samples/logging/pytest/test_sample.py
Some of the imported modules were not used. Remove those.
> samples: logging: pytest: cleanup import modules list

- samples/dfu/sample.yaml
Disable settings support in system client, so that PSK-ID and PSK will be
pulled in from environment variables and baked into the firmware. This
allows to omit credentials provisioning.
This is a follow-up of commit 6f1e59270834 ("samples: dfu: disable settings
in system client for NCS runtime test").
> samples: dfu: disable settings in system client for vanilla Zephyr tests

- samples/dfu/README.rst
By referencing `$(west topdir)` the whole command can be simply copy-pasted
by user and it will work as is, instead of requiring to manually replace
`WEST_ROOT` with the directory where west was initialized.
> samples: dfu: README: use $(west topdir) instead of WEST_ROOT

- samples/dfu/pytest/test_sample.py
Convert all `os.path.*` invocations to `pathlib`, in order to improve code
readability and consistency.
> samples: dfu: pytest: convert os.path.* to pathlib

- samples/common/Kconfig
- samples/dfu/pytest/conftest.py
- samples/dfu/pytest/test_sample.py
- samples/dfu/sample.yaml
- samples/lightdb/delete/pytest/conftest.py
- samples/lightdb/delete/pytest/test_sample.py
- samples/lightdb/delete/sample.yaml
- samples/lightdb/get/pytest/conftest.py
- samples/lightdb/get/pytest/test_sample.py
- samples/lightdb/get/sample.yaml
- samples/lightdb/observe/pytest/conftest.py
- samples/lightdb/observe/pytest/test_sample.py
- samples/lightdb/observe/sample.yaml
- samples/lightdb/set/pytest/conftest.py
- samples/lightdb/set/pytest/test_sample.py
- samples/lightdb/set/sample.yaml
- samples/lightdb_led/pytest/conftest.py
- samples/lightdb_led/pytest/test_sample.py
- samples/lightdb_led/sample.yaml
- samples/lightdb_stream/pytest/conftest.py
- samples/lightdb_stream/pytest/test_sample.py
- samples/lightdb_stream/sample.yaml
- samples/logging/pytest/conftest.py
- samples/logging/pytest/test_sample.py
- samples/logging/sample.yaml
- samples/rpc/pytest/conftest.py
- samples/rpc/pytest/test_sample.py
- samples/rpc/sample.yaml
Introduce connect timeout as a build configuration, so that test scripts
will know how much time to wait before considering connection timeout.
Having it as Kconfig option allows to configure it per platform and per
connectivity requirements.
This replaces custom `--initial-timeout` pytest argument, which resulted in
duplicating test cases for fast (default 30s) / long (configured 120s)
timeouts.
> samples: introduce GOLIOTH_SAMPLE_TEST_CONNECT_TIMEOUT

- samples/dfu/pytest/test_sample.py
Remove one hardcoded `dfu` project name in order to be able to quickly
move (copy-paste) this test to other directory/sample.
Do not hardcode new firmware version (`2.0.0`) globally and move it into the
test itself. This will allow to develop more DFU tests, that allow to test
a flow with multiple rollouts (thus multiple versions).
Introduce a `Firmware` helper class, which will store both the path and the
version of the firmware. Use `imgtool` package in order to figure out the
version automatically from file name (in the context where only a firmware
object is passed).
> samples: dfu: pytest: reduce hardcoded global variables

- net/golioth/Kconfig
- net/golioth/rpc.c
Introduce GOLIOTH_RPC_MAX_RESPONSE_LEN which allows applications to change the max size of the CBOR response returned from an RPC method. This solves
the issue of receiving an error when the RPC response is too large: <err>
golioth: QCBOREncode_FinishGetSize error: 1 (QCBOR_ERR_BUFFER_TOO_SMALL)
> net: golioth: Kconfig for max CBOR RPC response

- .gitlab-ci.yml
Don't issue `west forall -c ...` to cleanup west projects, as they should
no longer contain unstaged changes.
Fixes: a93f9f13dc46 ("ci: replace 'git apply' with 'git am' when applying patches")
> gitlab-ci: remove remaining `west forall ...` invocations

- README.rst
Fixes broken link in README and changes terminology to "Authentication" rather than "CoAP Authentication" as auth is enabled by DTLS, which is not tightly coupled to the usage of CoAP.
> fix: correct broken link in README

- net/golioth/rpc.c
Verify length of method name, so that comparison between registered (from
application view) method name "app_method_2" is not invoked when there is
an RPC call of "app_method".
> rpc: verify length of method name

- samples/lightdb/set/sample.yaml
Logs are not used during twister runtime test, so disable them.
> samples: lightdb: set: disable Golioth log backend in twister

- logging/Kconfig
With Zephyr logging v2 there was an overhaul of Kconfig options. At first
old options were supported to some point. Right now there is no
`LOG_IMMEDIATE`, which `LOG_BACKEND_GOLIOTH` depended on.
Change `LOG_IMMEDIATE` to `LOG_MODE_IMMEDIATE`. This makes sure that for
platforms with synchronous logging by default (like recently introduced
`native_sim` in upstream Zephyr) Golioth logging backend doesn't get
enabled.
> logging: depend on LOG_MODE_IMMEDIATE

- net/golioth/Kconfig
- net/golioth/system_client.c
PSK-ID length was always hardcoded to maximum 64 characters. As a result
long project names with long PSK-IDs (due to
`long-device-id@long-project-name` PSK-ID format) would not be supported.
PSK had the same issue, but only when used with NCS.
Introduce options for both, PSK-ID and PSK, so that long credentials can be
supported without changing SDK codebase.
Alternative to: #359
> kconfig: add options for maximum PSK-ID and PSK lengths

- .github/workflows/gitlint.yml
- .github/workflows/pre-commit.yml
There is a newest version of that tool available, so simply use it.
> bump CI Docker images for gitlint and pre-commit

- net/golioth/settings.c
When there are no settings, then Golioth cloud sends "settings" map entry with 'null' (primitive 22) as value. Handle that by explicitly.
> settings: gracefully handle the case with empty settings

- samples/hello_sporadic/CMakeLists.txt
- samples/hello_sporadic/README.rst
- samples/hello_sporadic/sample.yaml
`s/hello/hello_sporadic/` in few places, so that the project name is unique
in all contexts (cmake, twister, ...).
Fix README title adornment length.
> samples: hello_sporadic: minor project name cleanup

- .github/workflows/build_test.yml
- .gitlab-ci.yml
Since there were two invocations of twister in a row, first `twister-out`
directory was renamed during second invocation. Additionally `reports/`
directory contents from first run got overwritten with contents from second
run. This means that artifacts from first run were never accessible.
Run twister with `--no-clean` option, so that single `twister-out`
directory is used. Test sets from both runs are unique, which means that
the result will be a merged directory structure containing artifacts from
both runs.
Use separate `reports/` directory, so that reports from both runs are
uploaded and available to be investigated.
> gitlab-ci: use separate output directories for {non-,}golioth tests

- net/golioth/Kconfig
- net/golioth/golioth.c
Creating an extra #ifdef conditional for handling recv flags when the connection socket is offloaded. ZSOCK_MSG_TRUNC is not supported on the nRF9160 modem firmware/library.
Fixes #417 
Signed-off-by: Jared Wolff (Circuit Dojo LLC)
> Remove ZSOCK_MSG_TRUNC for offloaded TLS on nRF9160.

- samples/dfu/README.rst
- samples/hello/README.rst
- samples/hello/sample.yaml
- samples/hello_sporadic/README.rst
- samples/lightdb/delete/README.rst
- samples/lightdb/get/README.rst
- samples/lightdb/observe/README.rst
- samples/lightdb/set/README.rst
- samples/lightdb_led/README.rst
- samples/lightdb_stream/README.rst
- samples/logging/README.rst
- samples/settings/README.rst
OVERLAY_CONFIG was deprecated in favor of EXTRA_CONF_FILE in 6a98c198d8f3
> samples: Use EXTRA_CONF_FILE instead of OVERLAY_CONFIG

- west-ncs.yml
This release has just few bugfix commits, so the impact should be minimal.
Among other things, there is a fix for nRF53 (which is a host MCU on
nRF7002-DK) that might be useful for downstream users.
> bump NCS to 2.4.1

- .gitlab-ci.yml
gitlint is already part of Docker image, so there is no need to install it
manually.
There is already `$CI_DEFAULT_BRANCH` provided by GitLab CI, so use it
instead of hardcoded `main`.
Introduce global `$MODULE_PATH`, so that `modules/lib/golioth` does not
need to be hardcoded in multiple places.
> gitlab-ci: drop gitlint and use generalize by using environment variables

- .github/workflows/build_test.yml
- net/golioth/CMakeLists.txt
- net/golioth/coap_req.c
- net/golioth/golioth.c
- net/golioth/include_random/zephyr/random/random.h
- patches/west-zephyr/zephyr/0001-twister-support-attach_serial_after_flash-in-hardwar.patch
- west-ncs.yml
- west-zephyr.yml
Bump Zephyr to latest release candidate to test it before final 3.5.0
release.
Bump NCS to tip of main (slightly newer than 2.5.0-rc1 tag), to find
potential nRF91* platform regressions.
Replace `rand32.h` with `random.h` to suppress header deprecation warning. Add
a workaround for older Zephyr versions (like the one used by NCS fork) by
providing `random.h` just for internal Golioth SDK library visibility.
Tested on:
> bump Zephyr to 3.5.0-rc3 and NCS to tip of main (2.5.0-rc1+)

- README.rst
- samples/certificate_provisioning/README.rst
- samples/dfu/README.rst
- samples/hello/README.rst
- samples/hello_sporadic/README.rst
- samples/lightdb/delete/README.rst
- samples/lightdb/get/README.rst
- samples/lightdb/observe/README.rst
- samples/lightdb/set/README.rst
- samples/lightdb_led/README.rst
- samples/lightdb_stream/README.rst
- samples/logging/README.rst
- samples/rpc/README.rst
- tests/lightdb/README.rst
- west-zephyr.yml
This is the latest stable release, with mostly documentation updates
compared to -rc3.
> bump Zephyr to 3.5.0

- .github/workflows/build_test.yml
- .gitlab-ci.yml
Twister treats overflows in the RAM during builds as "skipped" tests instead of errors by default. Enabling the `--overflow-as-errors` option ensures we can catch overflows in CI.
> ci: catch ram overflow build failures

- net/golioth/Kconfig
- net/golioth/golioth.c
- samples/hello/sample.yaml
Enable Connection ID support, which enables deviecs to maintain their connection with the server for longer periods and across IP address changes, resulting in lower bandwidth and reduced power usage.
> dtls: enable DTLS 1.2 Connection IDs

- .github/workflows/test_nrf52840dk.yml
- .github/workflows/test_nrf9160dk.yml
Target self-hosted runners using the `is_active` label. We added this label to all of our self-hosted runners to indicate they are ready to be assigned CI tests. Removing this label (for maintenance or testing) from a runner removes it from the CI loop.
> workflows: used is_active to select runner

- net/golioth/CMakeLists.txt
- net/golioth/ot_dns.c
- net/golioth/ot_dns.h
- net/golioth/system_client.c
Avoid hardcoding the IPv6 Golioth System Server address by leveraging OpenThread DNS to retrieve the address before connecting to Golioth Cloud. As a side benefit, NAT64 prefix used by the Thred Border Router is set while synthesizing the address.
> OpenThread: avoid hardcoded Golioth IPv6 address

- samples/dfu/src/main.c
Add message when a release number is received from Golioth that doesn't match what is currently running. This indicates an OTA firmware update should be performed (it will either be an update or a rollback). This change compliments the message we log when the received semantic version matches what is currently running on the device.
> samples: dfu: add log for different release number

- net/golioth/coap_req.c
- net/golioth/fw.c
Fix undefined behavior related to `free()` of uninitialized pointer. Just
return early when allocation with `golioth_coap_req_new()` has failed.
Free `coap_req` when scheduling it for sending has failed.
> coap_req: fix use alloc/free issues

- .github/workflows/checkpatch.yml
- .github/workflows/firebase-doxygen-main.yml
- .github/workflows/firebase-doxygen-pr.yml
- .github/workflows/gitlint.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test_nrf52840dk.yml
- .github/workflows/test_nrf9160dk.yml
- samples/test/verify.py
By default, USB hubs are turned off after tests. Update workflows that run on HIL to turn on the hub at the start of the test, and erase and turn off the hub after it runs.
resolve https://github.com/golioth/firmware-issue-tracker/issues/501
> workflows: add USB hub control to workflows
